### ISSUE TITLE
报错解决了

### ISSUE THREAD

**Issue by gstar12** [douhaohaode/NovelT#2]
环境：win10，python3.8，我没有安装conda环境，只是安装了python，普通用pip安装环境
最开始报错是basicsr的原因，因为找不到basicsr目录，我安装的目录名是basicsr-1.4.2.dist-info，我删除了basicsr用这命令pip uninstall basicsr然后又安装了pip install basicsr，现在是运行报错如下：
C:\Python\Python383\python.exe K:\novel\app.py 
Traceback (most recent call last):
  File "K:\novel\app.py", line 10, in <module>
    from cover import cover
  File "K:\novel\cover.py", line 2, in <module>
    import real_gan
  File "K:\novel\real_gan.py", line 3, in <module>
    from basicsr.archs.rrdbnet_arch import RRDBNet
  File "C:\Python\Python383\lib\site-packages\basicsr\__init__.py", line 4, in <module>
    from .data import *
  File "C:\Python\Python383\lib\site-packages\basicsr\data\__init__.py", line 22, in <module>
    _dataset_modules = [importlib.import_module(f'basicsr.data.{file_name}') for file_name in dataset_filenames]
  File "C:\Python\Python383\lib\site-packages\basicsr\data\__init__.py", line 22, in <listcomp>
    _dataset_modules = [importlib.import_module(f'basicsr.data.{file_name}') for file_name in dataset_filenames]
  File "C:\Python\Python383\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Python\Python383\lib\site-packages\basicsr\data\realesrgan_dataset.py", line 11, in <module>
    from basicsr.data.degradations import circular_lowpass_kernel, random_mixed_kernels
  File "C:\Python\Python383\lib\site-packages\basicsr\data\degradations.py", line 8, in <module>
    from torchvision.transforms.functional_tensor import rgb_to_grayscale
ModuleNotFoundError: No module named 'torchvision.transforms.functional_tensor'
麻烦帮助看一下什么原因，我也是安装  pip install requirements.txt 所有的，安装时都正常没有报错

没事了，我解决掉了

**Comment by yuren2333** [comment]
请教一下是如何解决的？
我用了win8和win10的环境 
首先都是尝试了普通pip安装，使用的是python3.10.11的版本，因为有一台可以运行的版本就是这个，但是可以成功运行的那一台电脑里面的python.exe大小为0，所以没有实际的安装意义，因为不知道怎么成功的。其他的电脑也是按照pip安装库这一套流程，但是一直提示gradio这个库找不到，实际是下过很多次了，python的环境变量也是设置在第一个。
后面开始尝试用up给的方法来安装，一套流程下来还是无法打开，也是提示gradio库找不到。
再后面是用pycharm来打开这个项目，解释器配置的3.10.11的版本，用pycharm的终端下载好了库，依然会有报错。
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\NovelT-main\app.py", line 2, in <module>
    import gradio as gr
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio.components as components
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\components\__init__.py", line 1, in <module>
    from gradio.components.annotated_image import AnnotatedImage
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\components\annotated_image.py", line 12, in <module>
    from gradio import utils
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\utils.py", line 38, in <module>
    import matplotlib
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib\__init__.py", line 263, in <module>
    _check_versions()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\matplotlib\__init__.py", line 257, in _check_versions
    module = importlib.import_module(modname)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\kiwisolver\__init__.py", line 8, in <module>
    from ._cext import (
ImportError: DLL load failed while importing _cext: 找不到指定的模块。
上面就是报错的原因，问了chatgpt让我给库文件夹site-packages设置环境变量我也设置了，文件夹里面也能找到gradio这个模块还有其他的，但是就是一直报错。麻烦帮我看一下，每次重新安装都重装了系统，怕有什么冲突，但是一直都不能成功运行。

**Comment by 1103887452** [comment]
Traceback (most recent call last):
  File "E:\NovelT-main\app.py", line 6, in <module>
    import cover
  File "E:\NovelT-main\cover.py", line 2, in <module>
    import real_gan
  File "E:\NovelT-main\real_gan.py", line 3, in <module>
    from basicsr.archs.rrdbnet_arch import RRDBNet
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\basicsr\__init__.py", line 4, in <module>
    from .data import *
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\basicsr\data\__init__.py", line 22, in <module>
    _dataset_modules = [importlib.import_module(f'basicsr.data.{file_name}') for file_name in dataset_filenames]
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\basicsr\data\__init__.py", line 22, in <listcomp>
    _dataset_modules = [importlib.import_module(f'basicsr.data.{file_name}') for file_name in dataset_filenames]
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\basicsr\data\realesrgan_dataset.py", line 11, in <module>
    from basicsr.data.degradations import circular_lowpass_kernel, random_mixed_kernels
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\basicsr\data\degradations.py", line 8, in <module>
    from torchvision.transforms.functional_tensor import rgb_to_grayscale
ModuleNotFoundError: No module named 'torchvision.transforms.functional_tensor'

现在报错和楼主一样了，请问楼主是如何解决的？
最开始是pycharm一直没有找到我在cmd窗口pip下载的包，然后我在pycharm的终端下载的包才能够识别，因为网速的原因尝试用国内源下载，但是运行到basicsr会报错，然后发现国内源里面没有找到这个包，试了几个都没办法，然后还是老老实实下载的。最后下载完成了，但是有出现和楼主一样的报错，尝试发现报错的这几个模块都没有找到，在安装的过程中发现在安装gfpgan==1.3.8的时候里面会有torch另一个版本好像是2.4.1的版本,在安装torch==2.0.1的时候会将torch另外一个版本给卸载掉,最后运行的时候就和楼主的报错一样,chatgpt让我更新torchvision,试了一下没有用,不知道是不是gfpgan需要用到torch另一个版本所以才会报错,但是我不知道怎么解决这个版本冲突的问题.不知道有没有什么解决办法?
